services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2512
      POSTGRES_DB: project
    networks:
      - bekhruz

  exam-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 2512
      DATABASE_NAME: project
    networks:
      - bekhruz

networks:
  bekhruz:
    driver: bridge